### ISSUE TITLE
Outdated Android Support Library

### ISSUE THREAD

**Issue by frodfigu** [williamrijksen/com.williamrijksen.onesignal#102]
From today I'm started to see this error "Outdated Android Support Library" on my One Signal Dashboard.

I'm using the 2.1.1 Android version of this module. And the devices doesn´t receive the notification pushes.

I'm using <uses-sdk android:minSdkVersion="19" android:targetSdkVersion="29"/> on my tiapp.xml

Can you help me?

**Comment by frodfigu** [comment]
I have this errors on launch my app:

[ERROR] OneSignal: The Firebase FCM library is missing! Please make sure to include it in your project.
[ERROR] OneSignal: The included Android Support Library is to old or incomplete. Please update to the 26.0.0 revision or newer.

[ERROR] OneSignal: Unknown error getting GCM Token
[ERROR] OneSignal: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/gcm/GoogleCloudMessaging;
[ERROR] OneSignal:      at com.onesignal.PushRegistratorGCM.getToken(PushRegistratorGCM.java:41)
[ERROR] OneSignal:      at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)
[ERROR] OneSignal:      at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)
[ERROR] OneSignal:      at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)
[ERROR] OneSignal:      at java.lang.Thread.run(Thread.java:919)
[ERROR] OneSignal: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GoogleCloudMessaging" on path: DexPathList[[zip file "/data/app/com.op.palapala-P1ELxMxsKeFZfLTvorN7Eg==/base.apk"],nativeLibraryDirectories=[/data/app/com.op.palapala-P1ELxMxsKeFZfLTvorN7Eg==/lib/arm64, /data/app/com.op.palapala-P1ELxMxsKeFZfLTvorN7Eg==/base.apk!/lib/arm64-v8a, /system/lib64]]
[ERROR] OneSignal:      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
[ERROR] OneSignal:      at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[ERROR] OneSignal:      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[ERROR] OneSignal:      ... 5 more

**Comment by frodfigu** [comment]
Solved by adding this configuration:

`<module platform="android" version="2.1.2">com.williamrijksen.onesignal</module>`
`<module platform="android" version="17.5.0">ti.playservices</module>`
`<module platform="android" version="6.0.0">firebase.core</module>`
`<module platform="android" version="3.0.1">firebase.cloudmessaging</module>`
