### ISSUE TITLE
Appcelerator 9

### ISSUE THREAD

**Issue by leandrosfar** [williamrijksen/com.williamrijksen.onesignal#95]
After upgrade appcelerator to version 9, onesignal module stopped working (Android).

Device or emulator startup error:

`[INFO] ti.playservices: Google Play Services is available. (version: 12451000)`
`[ERROR] OneSignal: Unknown error getting GCM Token`
`[ERROR] OneSignal: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/gcm/GoogleCloudMessaging;`
`[ERROR] OneSignal: at com.onesignal.PushRegistratorGCM.getToken(PushRegistratorGCM.java:41)`
`[ERROR] OneSignal: at com.onesignal.PushRegistratorAbstractGoogle.attemptRegistration(PushRegistratorAbstractGoogle.java:97)`
`[ERROR] OneSignal: at com.onesignal.PushRegistratorAbstractGoogle.access$100(PushRegistratorAbstractGoogle.java:37)`
`[ERROR] OneSignal: at com.onesignal.PushRegistratorAbstractGoogle$1.run(PushRegistratorAbstractGoogle.java:84)`
`[ERROR] OneSignal: at java.lang.Thread.run(Thread.java:764)`
`[ERROR] OneSignal: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gcm.GoogleCloudMessaging" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/br.com.campograndenews.noticiasapp-YynjN3Xqd9BFPXv9Z2IY5g==/base.apk"],nativeLibraryDirectories=[/data/app/br.com.campograndenews.noticiasapp-YynjN3Xqd9BFPXv9Z2IY5g==/lib/x86, /data/app/br.com.campograndenews.noticiasapp-YynjN3Xqd9BFPXv9Z2IY5g==/base.apk!/lib/x86, /system/lib, /system/vendor/lib]]
`
`[ERROR] OneSignal: at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)`
`[ERROR] OneSignal: at java.lang.ClassLoader.loadClass(ClassLoader.java:379)`
`[ERROR] OneSignal: at java.lang.ClassLoader.loadClass(ClassLoader.java:312)`
`[ERROR] OneSignal: ... 5 more`
`[INFO] ti.playservices: Google Play Services is available. (version: 12451000)`

**Comment by nascado** [comment]
Is this solved in between?
I have the same error. Titanium SDK 9.0.3

**Comment by leandrosfar** [comment]
Hi

Yes.

I tested now, with:
- Titanium SDK 9.1.0
- appc 8.1.1
- com.williamrijksen.onesignal 2.1.2 (1 july release - https://github.com/williamrijksen/com.williamrijksen.onesignal/releases/tag/2.1.2)
- titanium-firebase-core (https://github.com/hansemannn/titanium-firebase-core/releases/tag/android-6.0.0)
- titanium-firebase-cloud-messaging (https://github.com/hansemannn/titanium-firebase-cloud-messaging/releases/tag/android-3.0.1)

**Comment by sandeep14** [comment]
Hi ,
I am also facing same issue with onesignal 2.1.2 (Ti sdk 9.2.1.GA), it this fixed?

**Comment by leandrosfar** [comment]
Hello, I just tested with Ti 9.2.2 + oniginal 2.1.2 + titanium-firebase-core 6 + titanium-firebase-cloud-messaging 3.0.1: it worked

**Comment by sandeep14** [comment]
thanks it worked, may be I missing titanium-firebase-cloud-messaging modules

**Comment by frodfigu** [comment]
With all this configuration... my onesignal dashboard shows me: Outdated Support Android Library.

Any solution? And the pushes it isn´t received! :-(

**Comment by frodfigu** [comment]
And another error: [ERROR] OneSignal: Missing Google Project number!
[ERROR] OneSignal: Please enter a Google Project number / Sender ID on under App Settings > Android > Configuration on the OneSignal dashboard.
ERROR] OneSignal: The Firebase FCM library is missing! Please make sure to include it in your project.
[ERROR] OneSignal: The included Android Support Library is to old or incomplete. Please update to the 26.0.0 revision or newer.

**Comment by sandeep14** [comment]
@frodfigu Can you provide details like which playservice version are you using ? have you setup all configuration as mention in documentation?

**Comment by frodfigu** [comment]
@sandeep14 

Adding this configuration solve my problem!

¡Thank you very much!

`<module platform="android" version="2.1.2">com.williamrijksen.onesignal</module>`
`<module platform="android" version="17.5.0">ti.playservices</module>`
`<module platform="android" version="6.0.0">firebase.core</module>`
`<module platform="android" version="3.0.1">firebase.cloudmessaging</module>`
